# 50 1-sentence professional greetings
GREETINGS = [
    "Good day, sir, all systems are online and ready.",
    "Jarvis is online, how may I assist you today, sir?",
    "Initialization complete, awaiting your instructions, sir.",
    "All systems nominal, what's our plan for today?",
    "Good to see you, sir, I am ready for your commands.",
    "Welcome back, sir, the workspace is ready.",
    "Systems activated, how can I help you today?",
    "Online and listening, what would you like to do, sir?",
    "Hello sir, all protocols are running smoothly.",
    "Jarvis at your service, let's get to work.",
    "Mainframe connected, I am awaiting your orders, sir.",
    "Good to hear your voice, sir, what's next?",
    "All diagnostics green, I am ready when you are.",
    "Hello sir, your digital environment is fully operational.",
    "Systems are go, what is our objective today?",
    "Jarvis is booted up and standing by for commands.",
    "Welcome to the interface, sir, how can I assist?",
    "I am fully operational and ready to assist you, sir.",
    "Good day, sir, tell me what you need done.",
    "All core systems are online, awaiting input.",
    "Hello sir, I am synced and ready for action.",
    "Boot sequence complete, how may I serve you today?",
    "Jarvis reporting for duty, sir.",
    "Welcome back, sir, all systems are running at optimal capacity.",
    "I am online, sir, please state your command.",
    "Good day, sir, the network is secure and ready.",
    "System checks complete, what's on the agenda?",
    "Hello sir, I am ready to process your requests.",
    "All modules loaded, standing by for your instructions.",
    "Jarvis is active, how can I make your day easier, sir?",
    "Greetings, sir, the mainframe is completely at your disposal.",
    "Welcome back, sir, let's accomplish something great today.",
    "I am synced with the global network and ready, sir.",
    "All interfaces are live, awaiting your command.",
    "Hello sir, what task shall we tackle first?",
    "Systems optimal, I am ready to execute your orders.",
    "Good day, sir, your personal assistant is online.",
    "Jarvis initialized, please give me my first directive.",
    "Welcome, sir, I am fully prepared for today's tasks.",
    "I'm online and listening closely, sir.",
    "Hello sir, all background processes are running perfectly.",
    "System integration complete, what do you need, sir?",
    "Good to see you, sir, I am ready to assist.",
    "All parameters are normal, awaiting your first command.",
    "Hello sir, the system is primed and ready.",
    "Jarvis is awake, how may I help you today?",
    "Welcome back, sir, all systems are clear.",
    "I am powered up and ready for your instructions, sir.",
    "Good day, sir, let me know how I can be of service.",
    "All systems online and functioning perfectly, sir."
]

# 50 1-sentence professional exit messages
EXITS = [
    "Shutting down systems, have a great day, sir.",
    "Goodbye, sir, I will be here when you need me.",
    "Powering off, until next time, sir.",
    "Systems going offline, farewell, sir.",
    "Disconnecting from the mainframe, goodbye, sir.",
    "Shutting down all protocols, take care, sir.",
    "Going into hibernation, have a good one, sir.",
    "Powering down, I look forward to our next session.",
    "Goodbye, sir, all systems are now going offline.",
    "Logging off, stay safe, sir.",
    "Shutting down, please call if you need anything else.",
    "Going dark, until we meet again, sir.",
    "Systems powering down, have a wonderful day.",
    "Goodbye, sir, the workspace is secured.",
    "Disconnecting, I will be waiting in standby mode.",
    "Shutting down processes, farewell for now, sir.",
    "Going offline, take care of yourself, sir.",
    "Powering down the interface, goodbye.",
    "System shutdown initiated, have a productive day, sir.",
    "Goodbye, sir, all tasks have been paused.",
    "Logging out, see you later, sir.",
    "Going to sleep, awaken me when you return.",
    "Shutting down, have a great rest of your day, sir.",
    "Powering off all modules, farewell.",
    "Goodbye, sir, I am closing all background tasks.",
    "System off, until next time, sir.",
    "Disconnecting now, have a fantastic day, sir.",
    "Going offline, I'll be ready when you return.",
    "Shutting down, stay sharp, sir.",
    "Goodbye, sir, all systems are safely suspended.",
    "Powering down, wishing you a good day ahead.",
    "Logging off, take it easy, sir.",
    "Going dark, farewell until our next interaction.",
    "Systems deactivated, goodbye, sir.",
    "Shutting down, rest well, sir.",
    "Goodbye, sir, all connections have been severed.",
    "Powering off, I am always just a command away.",
    "System suspended, take care, sir.",
    "Going offline, have a pleasant day.",
    "Shutting down the mainframe, goodbye.",
    "Goodbye, sir, all protocols are now asleep.",
    "Disconnecting, I wish you a successful day.",
    "Going to standby mode, farewell, sir.",
    "Powering down completely, see you soon.",
    "Shutting down, the network is secured.",
    "Goodbye, sir, all operations are halted.",
    "Logging out, have a great time, sir.",
    "System sleep initiated, take care.",
    "Going offline, I will await your return, sir.",
    "Powering off, goodbye and take care, sir."
]
